name: Update Gallery Data

on:
  schedule:
    # Run once a month (first day of month at midnight)
    - cron: '0 0 1 * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Fetch spreadsheet data
        run: node fetch-data.js
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add gallery-data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update gallery data"
          git push
